// Shared glossary. Use [[term]] or [[term|shown text]] in any case text to get a hover definition.
// Keys are matched case-insensitively. Cases can add their own terms in CASE.glossary.
// Definitions: one or two plain sentences, no jargon that isn't itself defined here.
window.GLOSSARY = {
  // --- basic biology ---
  'DNA': 'The long molecule that stores genetic instructions. Genes are stretches of DNA that encode proteins.',
  'RNA': 'A working copy of a gene. Messenger RNA (mRNA) carries the instructions from DNA to the cell\'s protein-making machinery.',
  'mRNA': 'Messenger RNA: a temporary copy of a gene that a cell reads to build a protein. mRNA vaccines deliver one on purpose.',
  'protein': 'A molecule built from a chain of amino acids that folds into a shape. Proteins do almost all the work in a cell: enzymes, receptors, signals, structure.',
  'gene': 'A stretch of DNA with the instructions for making one protein (or a functional RNA).',
  'mutation': 'A change in the DNA sequence. Some are harmless; some break a protein or make it overactive.',
  'enzyme': 'A protein that speeds up a specific chemical reaction. Many drugs work by blocking an enzyme.',
  'receptor': 'A protein, often on the cell surface, that detects a signal (a hormone, a neighbouring cell\'s protein) and triggers a response inside the cell.',
  'kinase': 'An enzyme that attaches phosphate groups to other proteins, switching them on or off. Kinases relay growth signals, so an always-on kinase can drive cancer.',
  'antigen': 'Any molecule the immune system can recognize, usually a piece of protein. Vaccines teach the immune system a specific antigen.',
  'T cell': 'A white blood cell that can recognize and kill infected or cancerous cells. Its T-cell receptor reads fragments of proteins displayed on other cells.',
  'B cell': 'A white blood cell that makes antibodies.',
  'cytokine': 'A small signaling protein immune cells use to talk to each other. Too much at once can cause a dangerous "cytokine storm".',
  'cytokine release syndrome': 'A dangerous flood of cytokines when many immune cells activate at once. It causes fever, low blood pressure and, at worst, organ failure.',
  'inflammation': 'The immune system\'s response to injury or infection: swelling, heat, redness. When it doesn\'t switch off, it damages tissue (as in rheumatoid arthritis).',
  'immune checkpoint': 'A built-in brake on T cells that stops them attacking healthy tissue. Some tumors exploit these brakes to hide.',
  'motor neuron': 'A nerve cell that carries signals from the spinal cord to muscles. When motor neurons die, muscles weaken and waste.',
  'amyloid': 'Protein fragments that clump together. In Alzheimer\'s disease, amyloid-beta forms plaques between brain cells.',
  'tau': 'A protein that forms tangles inside neurons in Alzheimer\'s disease. Tangles track symptoms more closely than amyloid plaques do.',
  'cholesterol': 'A fatty molecule carried in the blood by lipoproteins. LDL ("bad") deposits it in artery walls; HDL ("good") carries it away.',
  'LDL': 'Low-density lipoprotein, the particle that carries cholesterol into artery walls. Lowering LDL reliably reduces heart attacks.',
  'HDL': 'High-density lipoprotein, which carries cholesterol away from tissues. People with high HDL have fewer heart attacks, but raising it with drugs has not helped.',
  'insulin': 'A hormone made by the pancreas that lets cells take up sugar from the blood. Type 1 diabetes: no insulin. Type 2: the body responds to it poorly.',
  'HbA1c': 'A blood test showing average blood sugar over the past 2–3 months. The standard measure of diabetes control.',
  'hormone': 'A chemical messenger released into the blood that acts on distant organs (insulin, GLP-1, oestrogen).',
  'virus': 'A tiny infectious particle that hijacks cells to copy itself. It has genes (DNA or RNA) in a protein coat.',
  'chromosome': 'A long, tightly packaged DNA molecule. Humans have 23 pairs.',

  // --- drug types (modalities) ---
  'modality': 'What kind of thing a medicine is: a small molecule, an antibody, a cell therapy, a gene therapy, an RNA drug, and so on.',
  'small molecule': 'A drug made by chemistry, small enough to get inside cells and usually taken as a pill (aspirin, imatinib).',
  'biologic': 'A drug made by living cells rather than chemistry, usually a large protein such as an antibody. Injected, not swallowed, and hard to copy exactly.',
  'antibody': 'A Y-shaped immune protein that grabs one specific target very tightly. Engineered versions (monoclonal antibodies) are the biggest class of biologic drugs.',
  'monoclonal antibody': 'Many identical copies of one antibody, made in cell factories. Drug names ending in "-mab" are monoclonal antibodies.',
  'ADC': 'Antibody-drug conjugate: an antibody with a potent toxin chemically attached. The antibody delivers the toxin to cells carrying its target.',
  'payload': 'The toxic drug carried by an antibody-drug conjugate.',
  'linker': 'The chemical tether joining an ADC\'s antibody to its payload. It must hold in the blood and release inside the target cell.',
  'cell therapy': 'A treatment made of living cells, often the patient\'s own immune cells, engineered and infused back.',
  'CAR-T': 'A cell therapy where a patient\'s T cells are given a chimeric antigen receptor (CAR) that makes them hunt cells with a chosen target, such as CD19 on B-cell cancers.',
  'gene therapy': 'Delivering a working copy of a gene into a patient\'s cells, usually with a harmless virus as the courier.',
  'AAV': 'Adeno-associated virus: a harmless virus stripped of its own genes and used as a courier to deliver a gene into cells.',
  'vector': 'The delivery vehicle for a gene therapy, usually an engineered virus such as AAV or a lentivirus.',
  'antisense oligonucleotide': 'A short, chemically modified strand of nucleic acid that sticks to a specific RNA and changes what the cell does with it: blocks it, destroys it, or alters how it is spliced.',
  'ASO': 'Antisense oligonucleotide: a short synthetic strand that binds a specific RNA to change how it is processed or read.',
  'splicing': 'The editing step that cuts non-coding pieces (introns) out of a gene\'s RNA copy and joins the useful pieces (exons) together.',
  'lipid nanoparticle': 'A tiny fat bubble that protects fragile RNA and helps it enter cells. The delivery system behind mRNA vaccines.',
  'peptide': 'A short chain of amino acids, smaller than a protein. GLP-1 drugs are peptides.',
  'vaccine': 'A medicine that trains the immune system to recognize a pathogen (or a tumor) before real exposure.',
  'biosimilar': 'A near-copy of a biologic made by another company after patents expire. It is not identical, so approval needs more evidence than a generic.',
  'generic': 'An exact chemical copy of a small-molecule drug, sold after patents expire, usually at a fraction of the price.',
  'prodrug': 'An inactive compound the body converts into the active drug. Used to improve absorption or targeting.',
  'half-life': 'How long it takes for half the drug to be cleared from the body. Longer half-life means less frequent dosing.',

  // --- discovery & development ---
  'target': 'The molecule in the body a drug is designed to act on, usually a protein. Picking the right target is the biggest single bet in drug discovery.',
  'target validation': 'Evidence that changing a target will actually help patients. Human genetics is the strongest kind.',
  'mechanism of action': 'How a drug produces its effect: what it binds, and what changes downstream.',
  'lead compound': 'A promising molecule chosen for optimization into a drug candidate.',
  'preclinical': 'Testing in cells and animals before any human is dosed, including the safety studies regulators require.',
  'IND': 'Investigational New Drug application: permission from the FDA to start testing a drug in people.',
  'first-in-human': 'The first time a new drug is given to people, normally at a tiny dose in a few healthy volunteers.',
  'phase 1': 'First trials in people (often 20–100). The main question: is it safe, and at what dose?',
  'phase 2': 'Trials in a few hundred patients. Does it seem to work, and at which dose?',
  'phase 3': 'Large trials (hundreds to thousands) that compare the drug with standard care or placebo to prove it works well enough to approve.',
  'phase 4': 'Studies after approval, to monitor long-term safety or test new uses.',
  'pivotal trial': 'The trial (or trials) whose results a regulator relies on to approve the drug.',
  'biomarker': 'A measurable sign in the body (a gene mutation, a protein level, a scan result) used to pick patients or track a drug\'s effect.',
  'companion diagnostic': 'A test that must be done to decide whether a patient is eligible for a specific drug.',
  'surrogate endpoint': 'A lab or scan measure (cholesterol, tumor size, plaque on a brain scan) used in place of what patients care about (heart attacks, survival, memory). Faster to measure, but it can mislead.',
  'endpoint': 'What a trial measures to decide whether the drug worked.',
  'primary endpoint': 'The single main outcome a trial is designed and powered to test. Success or failure is judged on it.',
  'overall survival': 'How long patients live after starting treatment. The gold-standard endpoint in cancer.',
  'progression-free survival': 'How long patients live without their cancer growing. Faster to measure than overall survival.',
  'response rate': 'The share of patients whose tumors shrink by a set amount (usually at least 30%).',
  'placebo': 'A dummy treatment with no active drug, used so the comparison shows the drug\'s real effect.',
  'randomized controlled trial': 'A trial where patients are assigned by chance to the new treatment or a comparison, so any difference is due to the treatment.',
  'double-blind': 'Neither patients nor doctors know who got the drug, so expectations can\'t bias results.',
  'open-label': 'Everyone knows who is getting which treatment.',
  'hazard ratio': 'The rate of a bad event (death, progression) in the treated group divided by the rate in the control group. 0.6 means a 40% lower rate at any given time.',
  'p-value': 'Roughly: how surprising the result would be if the drug did nothing. Below 0.05 is the usual bar for "statistically significant".',
  'confidence interval': 'The range of plausible true effects given the data. A narrow interval means a precise estimate.',
  'Kaplan-Meier curve': 'A chart of the share of patients still alive (or event-free) over time. Curves that separate and stay apart mean a lasting benefit.',
  'median': 'The middle value: half the patients are above it and half below. "Median survival 12 months" means half lived longer than 12 months.',
  'interim analysis': 'A planned look at trial data before the end. If the result is overwhelming, or hopeless, the trial can stop early.',
  'futility analysis': 'An interim check of whether a trial has any realistic chance of succeeding. If not, it stops.',
  'data monitoring committee': 'Independent experts who look at unblinded trial data during a study to protect patients and decide on early stopping.',
  'adverse event': 'Any harmful or unwanted medical event during a trial or treatment, whether or not the drug caused it.',
  'off-target effect': 'An effect from the drug acting on something other than its intended target.',
  'dose-limiting toxicity': 'A side effect severe enough to stop the dose being raised further in a phase 1 trial.',
  'attrition': 'Drugs dropping out of development. Roughly 9 in 10 drugs that enter human trials never get approved.',
  'standard of care': 'The treatment doctors normally give for a condition today. New drugs are often tested against it.',
  'real-world evidence': 'Data from routine medical care (records, registries, claims) rather than a controlled trial.',
  'basket trial': 'A trial testing one drug in many cancer types that share the same molecular feature.',

  // --- regulatory ---
  'FDA': 'US Food and Drug Administration, which approves medicines for the US market.',
  'EMA': 'European Medicines Agency, which evaluates medicines for the European Union.',
  'NDA': 'New Drug Application: the dossier asking the FDA to approve a small-molecule drug.',
  'BLA': 'Biologics License Application: the equivalent of an NDA for biologics such as antibodies, vaccines and gene therapies.',
  'accelerated approval': 'An FDA route that approves a drug for a serious disease based on a surrogate endpoint, on condition that later trials confirm real benefit.',
  'priority review': 'FDA commitment to decide within 6 months instead of the standard 10.',
  'breakthrough therapy designation': 'An FDA designation for drugs showing early evidence of substantial improvement on a serious condition. It brings more FDA guidance and faster review.',
  'orphan drug': 'A drug for a rare disease (under 200,000 US patients). It brings 7 years of US market exclusivity and tax credits.',
  'advisory committee': 'Outside experts who publicly review an application and vote on it. The FDA usually, but not always, follows their advice.',
  'PDUFA date': 'The FDA\'s target date to decide on an application.',
  'label': 'The official prescribing information: which patients, at what dose, with which warnings. Selling a drug for uses outside the label is illegal.',
  'black box warning': 'The FDA\'s strongest safety warning, printed in a box at the top of a drug\'s label.',
  'emergency use authorization': 'A temporary FDA authorisation during a public-health emergency, with a lower evidence bar than full approval.',
  'REMS': 'Risk Evaluation and Mitigation Strategy: extra FDA-required safety controls, such as restricted prescribing or monitoring.',
  'withdrawal': 'Taking a drug off the market, by the company or on a regulator\'s demand.',
  'pharmacovigilance': 'Monitoring drugs for side effects after they reach the market.',

  // --- business ---
  'blockbuster': 'A drug with more than $1 billion in annual sales.',
  'patent cliff': 'The sharp revenue drop when a drug\'s key patents expire and cheaper copies launch.',
  'loss of exclusivity': 'The point when patents and regulatory protections end and copies can be sold.',
  'patent thicket': 'Dozens or hundreds of overlapping patents on one drug (formulations, manufacturing, uses) that delay competitors after the main patent expires.',
  'licensing deal': 'An agreement where one company pays another for rights to develop and sell a drug, usually as upfront cash plus milestones and royalties.',
  'upfront payment': 'Cash paid on signing a licensing deal, the only money guaranteed to change hands.',
  'milestone payment': 'A payment triggered by an event such as a trial success, an approval or a sales level. Most headline "deal values" are mostly milestones.',
  'royalty': 'A percentage of sales paid to the company that invented or licensed the drug.',
  'rNPV': 'Risk-adjusted net present value: future cash flows, each weighted by the probability of reaching it, discounted to today. The standard way to value a drug in development.',
  'list price': 'The official price before discounts and rebates. What payers actually pay (the net price) is often much lower.',
  'net price': 'What the manufacturer actually receives after rebates and discounts.',
  'payer': 'Whoever pays for the drug: insurers, government programmes such as Medicare, or national health systems.',
  'formulary': 'An insurer\'s list of covered drugs. Being left off can sink a launch.',
  'prior authorization': 'An insurer\'s requirement that a doctor get approval before a drug is covered.',
  'CMS': 'Centers for Medicare & Medicaid Services, the US agency that runs Medicare and decides much of what it pays for.',
  'cost-effectiveness': 'Whether a treatment\'s health gain justifies its cost, often measured in cost per QALY.',
  'QALY': 'Quality-adjusted life year: one year of perfect health. Used to compare value across treatments.',
  'ICER': 'Institute for Clinical and Economic Review, a US non-profit that estimates what price would make a drug cost-effective.',
  'CRO': 'Contract research organization: a company that runs clinical trials for drug developers.',
  'CDMO': 'Contract development and manufacturing organization: a company that makes drugs for other companies.',
  'CMC': 'Chemistry, manufacturing and controls: proving you can make the drug consistently at scale. A frequent cause of delays.',
  'platform': 'A reusable technology (mRNA, ADC linkers, antisense chemistry) that can produce many drugs, not just one.',
  'first-in-class': 'The first drug to work through a particular mechanism.',
  'best-in-class': 'The best drug among several with the same mechanism.',
  'fast follower': 'A drug with the same mechanism as a pioneer, developed quickly to share or take the market.',
  'venture philanthropy': 'A charity funding drug development in exchange for a share of future returns, as the Cystic Fibrosis Foundation did with Vertex.',
};
